LiveCoaching/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
# from allauth.account.urls import  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('order/', include('order.urls')),

    # allauth
    path('accounts/', include('allauth.urls')),

    path('favicon.ico', RedirectView.as_view(
        url='/static/images/favicon.ico')),
    path('zoom', include('zoom.urls'),)
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from home import views

urlpatterns = [
    path(
        '',
        views.home,
        name='home'
    ),
    path(
        'coaches',
        views.coaches,
        name='coaches'
    ),

    path(
        "password_reset",
        auth_views.PasswordResetView.as_view(
            template_name="password/password_reset.html"),
        name="password_reset"
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password/password_reset_confirm.html"),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'coach_details/<int:pk>',
        views.CoachDetailView.as_view(),
        name='coach_details'
    ),
    path(
        'booking/<int:pk>',
        # views.BookingDetailView.as_view(),
        views.booking,
        name='booking'
    ),
    path(
        'sessions',
        views.sessions,
        name='sessions'
    ),
    path(
        'get_coach_available_hours/<int:pk>/<str:_date>',
        views.get_coach_available_hours,
        name='get_coach_available_hours'
    ),
    path(
        "payment",
        views.payment_view,
        name='payment'

    ),
    path(
        'post_pay',
        views.post_pay,
        name='post_pay'
    ),
    path(
        'schedule_zoom_meeting',
        views.schedule_zoom_meeting,
        name='schedule_zoom_meeting'
    ),
    path(
        'zoom_schedule_callback',
        views.zoom_schedule_callback,
        name='zoom_schedule_callback'
    ),

    # admin panel
    path(
        'dashboard',
        views.dashboard,
        name='dashboard'
    ),
    path(
        'dashboard/manage_coaches', 
        views.CoachAdminListView.as_view(), 
        name='manage_coaches'
    ),
    path(
        'dashboard/manage_coaches/<int:coach_id>',
        views.coach_admin_update,
        name='manage_coach'
    ),
    path(
        'contact_us',
        views.contact_us,
        name='contact_us'
    ),

    path(
        'coach_stats',
        views.coach_stats,
        name='coach_stats'
    ),

    path(
        'client_stats',
        views.client_stats,
        name='client_stats'
    ),
    path(
        'session_stats',
        views.session_stats,
        name='session_stats'
    ),
        path(
        'sessions_per_coach',
        views.sessions_per_coach,
        name='sessions_per_coach'
    ),
        path(
        'sessions_per_client',
        views.sessions_per_client,
        name='sessions_per_client'
    ),
    path(
        'sessions_per_category',
        views.sessions_per_category,
        name='sessions_per_category'
    ),
    
  
    path(
        'navigate_to_meeting/<int:session_id>',
        views.navigate_to_meeting,
        name='navigate_to_meeting'
    ),
    path(
        'join_meeting',
        views.join_meeting,
        name='join_meeting'
    ),
    # url to get zoom sdk credentials
    path(
        'EmbdZmCrd',
        views.get_zoom_crd_creds,
        name='EmbdZmCrd'
    ),
    path(
        'get_sorted_coaches/<str:option>/<str:coach_name_q>/<str:coach_category_q>/<str:min_price_q>/<str:max_price_q>',
        views.get_sorted_coaches,
        name='get_sorted_coaches'
    ),
    path(
        'signup',
        views.signup_view,
        name='signup'
    ),

    path(
        'customer_messages',
        views.customer_messages,
        name='customer_messages'
    ),
    path(
        'close_customer_message',
        views.close_customer_message,
        name='close_customer_message'
    ),
    path(
        'promo_codes',
        views.promo_codes,
        name='promo_codes'
    ),
    path(
        'end_promo_code',
        views.end_promo_code,
        name='end_promo_code'
    ),
    path(
        'generate_new_promo_code',
        views.generate_new_promo_code,
        name='generate_new_promo_code'
    ),
    path(
        'validate_promo_code',
        views.validate_promo_code,
        name='validate_promo_code'
    ),
    path(
        'profile',
        views.profile,
        name='profile'
    ),
    path(
        'get_zoom_meeting_data/<int:session_id>',
        views.get_zoom_meeting_data,
        name='get_zoom_meeting_data'
    ),
    path(
        'profile_edit',
        views.profile_edit,
        name='profile_edit'
    ),
    path(
        'remove_certificate',
        views.remove_certificate,
        name='remove_certificate'
    ),
    path(
        'add_new_certificate_to_coach',
        views.add_new_certificate_to_coach,
        name='add_new_certificate_to_coach'
    ),
    path(
        'get_all_certificates',
        views.get_all_certificates,
        name='get_all_certificates'
    )



]

home/models.py
import datetime
import json
from time import time
from django.db.models.functions import TruncMonth, Length
from django.db.models import Count
import random
import string


import jwt
import requests
from creditcards.models import (CardExpiryField, CardNumberField,
                                SecurityCodeField)
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


from django.contrib.auth.models import AbstractUser


# TODO
# coach location filed options

class User(AbstractUser):
    city = models.CharField(max_length=50, default="not-provided")
    country = models.CharField(max_length=50, default="not-provided")
    gender = models.CharField(max_length=6, choices=(('Male','Male'), ('Female','Female')), blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20)

# make the email required for any user
User._meta.get_field('email').blank = False
User._meta.get_field('email').null = False


class ClientCustomManager(models.QuerySet):

    def get_monthly_stats(self):
        return self.annotate(month=TruncMonth('joined_at')).values('month').annotate(count=Count('id')).values('joined_at__month', 'count')

    def get_total_session_per_client(self):
        return self.annotate(no_of_session=Count('session')).values('user__username', 'no_of_session').order_by('no_of_session')

class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='photo/client/%Y/%m/%d', blank=True)
    
    
    objects = ClientCustomManager.as_manager()

    def __str__(self) -> str:
        return self.user.username

class Certificate(models.Model):
    name = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='certificate/coach', blank=True)
    coach = models.ForeignKey("Coach", on_delete=models.CASCADE, null=True, blank=True, related_query_name='certificates')

class CoachCustomManager(models.QuerySet):

    def get_monthly_stats(self):
        return self.annotate(month=TruncMonth('joined_at')).values('month').annotate(count=Count('id')).values('joined_at__month', 'count')

    def get_available_hours(self, pk, day):
        coach_list = self.filter(pk=pk)
        if coach_list.count() > 0:
            coach = coach_list[0]
            _date = datetime.datetime.combine(datetime.date(
                *[int(x) for x in day.split('-')]), coach.working_hours_start)

            total_duration = (
                datetime.datetime.combine(datetime.date.today(
                ), coach.working_hours_end) - datetime.datetime.combine(datetime.date.today(), coach.working_hours_start)
            ).seconds

            # execluding last half hour as the duration is 1 hour
            all_half_hours = (
                _date + datetime.timedelta(minutes=i/60) for i in range(0, total_duration, 60*30))

            formated_half_hours = [x.strftime('%H:%M') for x in all_half_hours][:-1]
            for i in coach.session_set.filter(time__date=_date):
                # remove reserved hour from all_half_hours
                if i.time.strftime('%H:%M') in formated_half_hours:
                    # remove current half hour
                    formated_half_hours.remove(i.time.strftime('%H:%M'))
                    
                     # remove next half hour
                    try:
                        formated_half_hours.remove(
                            (i.time + datetime.timedelta(minutes=30)).strftime('%H:%M')) 
                    except:
                        pass

                    # remove previous half hour
                    try:
                        formated_half_hours.remove(
                            (i.time - datetime.timedelta(minutes=30)).strftime('%H:%M')) 
                    except:
                        pass

            return formated_half_hours
        return []



class Coach(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=50)
    rating = models.IntegerField(default=0, validators=[
                                 MaxValueValidator(5), MinValueValidator(0)])
    location = models.CharField(max_length=150, default='Egypt')
    price_per_hour = models.IntegerField(default=0) # in 100 cents
    price_per_30_mins = models.IntegerField(default=0) # in 100 cents
    available_for_kids = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='photo/coach/%Y/%m/%d')
    working_hours_start = models.TimeField(default=datetime.time(8, 0, 0))
    working_hours_end = models.TimeField(default=datetime.time(16, 0, 0))
    joined_at = models.DateTimeField(auto_now_add=True)
    bio = models.CharField(max_length=255, null=True, blank=True)
    featured = models.BooleanField(default=False)
    # certificates = models.ManyToManyField(Certificate)

    objects = CoachCustomManager.as_manager()

    def __str__(self) -> str:
        return self.user.username

    def save(self, *args, **kwargs):
        self.location = f'{self.user.city}, {self.user.country}' 
        super(Coach, self).save(*args, **kwargs)


class SessionCustomManager(models.QuerySet):

    def get_monthly_stats(self):
        return self.annotate(month=TruncMonth('time')).values('month').annotate(count=Count('id')).values('time__month', 'count')

    def generate_zoom_token(self):
        API_KEY = settings.ZOOM_API_KEY
        API_SEC = settings.ZOOM_API_SEC
        token = jwt.encode(
            {'iss': API_KEY, 'exp': time() + 5000},
            API_SEC,
            algorithm='HS256'
        )
        return jwt.decode(token, API_SEC, algorithms=["HS256"])

    def get_upcomming_sessions(self):
        return self.filter(time__gte=datetime.datetime.now())

    def get_total_session_per_coach(self):
        return self.all().values('coach').annotate(count=Count('id')).values('coach__user__username', 'count').order_by('count')

    def get_total_session_per_category(self):
        return self.all().values('coach__category').annotate(count=Count('id')).values('coach__category', 'count').order_by('count')

    def create_zoom_meeting(self, topic, start_time, duration_in_mins, time_zone, agenda):
        formated_time = '2022-12-12T11: 11: 11'  # will be formated from start_time
        payload = {
            "topic": topic,
            "type": 2,
            "start_time": formated_time,
            "duration": duration_in_mins,
            "timezone": time_zone,
            "agenda": agenda,

            "recurrence": {"type": 1,
                           "repeat_interval": 1
                           },
            "settings": {"host_video": "true",
                         "participant_video": "true",
                         "join_before_host": "False",
                         "mute_upon_entry": "True",
                         "watermark": "true",
                         "audio": "voip",
                         "auto_recording": "cloud"
                         }
        }

        headers = {
            'authorization': f'Bearer {self.generate_zoom_token()}',
            'content/type': 'application/json'
        }

        response = requests.post(
            settings.ZOOM_API_URL,
            headers=headers,
            data=json.dumps(payload)
        )

        result = response.json()


class Session(models.Model):
    clients = models.ManyToManyField(Client)
    coach = models.ForeignKey(Coach, on_delete=models.CASCADE)
    time = models.DateTimeField()
    duration = models.IntegerField(default=60)
    review = models.CharField(max_length=500, default='')
    group_session = models.BooleanField(default=False)
    meeting = models.ForeignKey('ZoomMeeting', on_delete=models.CASCADE, null=True, blank=True)
    # url = models.URLField(default=None, null=True)

    objects = SessionCustomManager.as_manager()

    def __str__(self) -> str:
        return f'{self.coach.category}: {self.coach} : {self.time}'


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    item = models.ForeignKey(Session, on_delete=models.CASCADE)
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.client.user.username

class CustomerMessage(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    phone_number = PhoneNumberField(blank=True, null=True)
    closed = models.BooleanField(default=False)

class Payment(models.Model):
    shipment_address = models.CharField(max_length=150)
    chipment_phone = models.CharField(max_length=150)
    card_number = CardNumberField()
    expiry_date = CardExpiryField()
    security_code = SecurityCodeField()

    def _paymob_first_api_call(self):
        url = 'https://accept.paymob.com/api/auth/tokens'
        context = {"api_key": "ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnVZVzFsSWpvaWFXNXBkR2xoYkNJc0luQnliMlpwYkdWZmNHc2lPall5TURFd05Dd2lZMnhoYzNNaU9pSk5aWEpqYUdGdWRDSjkuNFpXTDFTemZfWC1FUEowcUtldXZ1VVN0WlJrU1dNNm0zRXFGZFlzNlZvS3ZZaEFBcFpSMGg1cURvVkNIZkd2MWFJUWFBSWRJbjZZaFlmejJwMkdqdEE="}
        r = requests.post(url, json=context)
        token = r.json().get('token')
        if token:
            return True, token
        return False, token

    def _paymob_seccond_api_call(
        self, 
        token, 
        merchant_order_id,
        amount_cents,
        item_name,
        quantity,
        email,
        first_name,
        last_name,
        phone_number,
        city,
        country
        ):
        url = 'https://accept.paymob.com/api/ecommerce/orders'
        merchant_order_id += 3000 # for testing
        print(merchant_order_id)

home/templates/home/admin_panel.html
{% extends 'base.html' %}
{% load static %}

{% block style %}


<link rel="stylesheet" href="{% static '/home/css/styles.css' %}">

<script>
    let coach_stats_url = "{% url 'coach_stats' %}";
    let client_stats_url = "{% url 'client_stats' %}";
    let session_stats_url = "{% url 'session_stats' %}";
    let sessions_per_coach_url = "{% url 'sessions_per_coach' %}";
    let sessions_per_client_url = "{% url 'sessions_per_client' %}";
</script>
<script src="{% static 'home/js/admin_panel.js' %}" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
{% endblock %}

{% block content %}
<!-- TODO -->
<!-- add number of messages , number of users as bell notification - float right -->
<div class="d-flex justify-content-between">
    <h3 class="m-3">Statistics</h3>
    <div>

    </div>
</div>

<div class="d-flex flex-column">
    <div class="d-flex justify-content-around">
    
    
        <div class="custom-card custom-narrow-card">
            <div class="d-flex justify-content-between">
                <div>
                    <div class="text-secondary">Coaches</div>
                    <h5>
                        <i class="fa fa-id-badge" aria-hidden="true"></i>
                        15
                    </h5>
                </div>
                <div></div>
            </div>
            <canvas id="coachChart"></canvas>
            <div class="text-end border-top py-3">
                <a href="{% url 'manage_coaches' %}" class="btn btn-warning">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div class="custom-card custom-narrow-card">
            <div class="d-flex justify-content-between">
                <div>
                    <div class="text-secondary">Clients</div>
                    <h5>
                        <i class="fa fa-user-circle" aria-hidden="true"></i>
                        48
                    </h5>
                </div>
                <div></div>
            </div>
            <canvas id="clientChart"></canvas>
            <div class="text-end border-top py-3">
                <a href="{% url 'manage_coaches' %}" class="btn btn-warning">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div class="custom-card custom-narrow-card">
            <div class="d-flex justify-content-between">
                <div>
                    <div class="text-secondary">Sessions</div>
                    <h5>
                        <i class="fa fa-users" aria-hidden="true"></i>
                        32
                    </h5>
                </div>
                <div></div>
            </div>
            <canvas id="sessionChart"></canvas>
      
        </div>
    
    </div>
    <div class="d-flex justify-content-around">
        <div class="custom-card custom-narrow-card">
            <div class="d-flex justify-content-between">
                <div>
                    <div class="text-secondary">Session Per Coach</div>
                    <h5>
                        <i class="fa fa-id-badge" aria-hidden="true"></i>
                        15
                    </h5>
                </div>
                <div></div>
            </div>
            <canvas style="height: 70%;" id="sessionPerCoachChart"></canvas>
            <!-- <div class="text-end border-top py-3">
                <a href="{% url 'manage_coaches' %}" class="btn btn-warning">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
            </div> -->
        </div>
        <div class="custom-card custom-narrow-card">
            <div class="d-flex justify-content-between">
                <div>
                    <div class="text-secondary">Session Per Client</div>
                    <h5>
                        <i class="fa fa-user-circle" aria-hidden="true"></i>
                        48
                    </h5>
                </div>
                <div></div>
            </div>
            <canvas style="height: 70%;" id="sessionPerClientChart"></canvas>
            <!-- <div class="text-end border-top py-3">
                <a href="{% url 'manage_coaches' %}" class="btn btn-warning">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
            </div> -->
        </div>
    </div>
</div>

<h3 class="m-3">Upcomming Sessions</h3>
    <div class="custom-card custom-ultra-wide-card">
        <div class="d-flex justify-content-between">
            <div>
                <div class="text-secondary">Use list group</div>
                <h5>
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    48
                </h5>
            </div>
            <div></div>
        </div>
        <canvas style="height: 70%;" id="sessionPerClientChart"></canvas>
    </div>

<h3 class="m-3">User Messages</h3>
    <div class="custom-card custom-ultra-wide-card">
        <div class="d-flex justify-content-between">
            <div>
                <div class="text-secondary">Use list group</div>
                <h5>
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    48
                </h5>
            </div>
            <div></div>
        </div>
        <canvas style="height: 70%;" id="sessionPerClientChart"></canvas>
    </div>
0{% endblock %}

home/templates/home/admin_panel1.html
{% extends 'base.html' %} 
{% load static %}

{% block style %}
    <link href="{% static 'home/css/styles.css' %}" rel="stylesheet">
    <script src="{% static 'home/js/admin_panel.js' %}" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
{% endblock %}

{% block content %}
<div class="container d-flex  justify-content-between mt-4 gap-3">
    <div class="card bg-light text-center w-50">
        <!-- <img src="{% static 'images/lc_6.jpg' %}" class="card-img" style="filter: brightness(60%);" alt="test"> -->
        <!-- <div class="card-img-overlay"> -->
            <div class="card-header" >
              Coaches
            </div>
            <div class="card-body">
               <div>
                <div class="d-flex justify-content-between mb-1">
                    <span>Life Coaches</span>
                    <span class="badge bg-primary rounded-pill">4</span>
                </div>
                <div class="d-flex justify-content-between mb-1">
                    <span>Career Coaches</span>
                    <span class="badge bg-primary rounded-pill">2</span>
                </div>
                <div class="d-flex justify-content-between mb-1">
                    <span>Relationship Coaches</span>
                    <span class="badge bg-primary rounded-pill">0</span>
                </div>

                <div class="d-flex justify-content-between mb-1">
                    <span>Relationship Coaches</span>
                    <span class="badge bg-primary rounded-pill">0</span>
                </div>
                <div class="d-flex justify-content-between mb-1">
                    <span>Relationship Coaches</span>
                    <span class="badge bg-primary rounded-pill">1</span>
                </div>

            </div>
            </div>
            <div class="card-footer text-end">
                <button class="btn btn-secondary">
                    <i class="bi bi-pencil"></i>
                </button>
                <button class="btn btn-danger">
                    <i class="bi bi-trash3"></i>
                </button>
            </div>
        </div>
      <!-- </div> -->
      <div class="card bg-light text-center  w-50">
        <!-- <img src="{% static 'images/lc_6.jpg' %}" class="card-img" style="filter: brightness(60%);" alt="test"> -->
        <!-- <div class="card-img-overlay"> -->
        
        <div class="card-header">
          Clients
        </div>
        <div class="card-body">
            <canvas id="clientChart"></canvas>
        </div>
        <div class="card-footer text-end">
                <button class="btn btn-secondary">
                    <i class="bi bi-pencil"></i>
                </button>
                <button class="btn btn-danger">
                    <i class="bi bi-trash3"></i>
                </button>
        </div>
        </div>
      <!-- </div> -->

      <div class="card bg-light text-center w-50">
        <div class="card-header">
          Sessoins
        </div>
        <div class="card-body">
            <canvas id="sessionChart"></canvas>
        </div>
        <div class="card-footer text-end">
                <button class="btn btn-secondary">
                    <i class="bi bi-pencil"></i>
                </button>
                <button class="btn btn-danger">
                    <i class="bi bi-trash3"></i>
                </button>

        </div>
      </div>
</div>
{% endblock %}

home/templates/home/sessions.html
{% extends 'base.html' %} 

{% load static %}


{% block style %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
<script src="{% static 'js/bootstrap.bundle.min.js' %}" defer></script>
<script src="{% static 'js/custom.js' %}" defer></script>

{% endblock %}



<!-- content block -->
{% block content %}
<div class="container-fluid">
  <div class="d-flex flex-column flex-lg-row justify-content-start m-3">

    <!-- Search Card -->
    <div class="m-3">
      <div class="card w-100">
        <div class="card-header">Filter By</div>

        <div class="card-body">
          <form method="GET" action="{% url 'coaches' %}">
            <div>
              <input
                type="text"
                id="nameInput"
                class="form-control"
                name="coach_name_q"
                placeholder="Coach Name ..."
              />
            </div>
            <div class="mt-2">
              <input
                type="text"
                id="categoryInput"
                class="form-control"
                name="coach_category_q"
                placeholder="Coach category ..."
              />
            </div>
            <hr />
            <div>
              <label class="form-label">Min Price</label>
              <div class="d-flex">
                <input
                  type="range"
                  value="0"
                  class="form-range me-2 slider"
                  id="minPriceInput"
                  name="min_price_q"
                  min="0"
                  max="1000"
                  oninput="this.nextElementSibling.value = this.value"
                />
                <output id="min_price_q_output">0</output>
              </div>
            </div>
            <div>
              <label class="form-label">Max Price</label>
              <div class="d-flex">
                <input
                  type="range"
                  value="1000"
                  class="form-range me-2 slider"
                  id="maxPriceInput"
                  name="max_price_q"
                  min="0"
                  max="1000"
                  oninput="this.nextElementSibling.value = this.value"
                />
                <output id="max_price_q_output">1000</output>
              </div>
            </div>
            <hr />
            <div hidden>
              <label class="form-label">Available In</label>
              <input type="date" class="form-control" name="available_date_q" />
            </div>
            <hr />
            <button type="submit" class="btn custom-btn-primary w-100 my-2">
              Search
            </button>
            <a href="{% url 'coaches' %}" class="btn custom-btn-danger w-100">Clear</a>
          </form>
        </div>
      </div>
    </div>

    <!-- Coaches Cards -->
    <div class="flex-grow-1 custom-text-primary">
      <h1>Group Sessions</h1>
      <div class="m-3 flex-grow-1">
        {% for session in session_list %}
        <div>
          <div class="card custom-text-primary mb-3">
            <div class="card-body d-flex justify-content-between">
              <div class="d-flex justify-content-between">
                <div>
                  <a href="#">
                    <img
                      src="{{ session.coach.photo.url }}"
                      class="coach-img img-fluid"
                      alt="coach-img"
                    />
                  </a>
                </div>
                <div>
                  <h4>{{session.coach.user.username}}</h4>
                  <p>{{session.coach.category}}</p>
                  <div>
                    <div>
                      {% if session.coach.rating > 0%}
                      <i class="fa-solid fa-star" style="color: gold"></i>
                      {% endif %} {% if session.coach.rating > 1%}
                      <i class="fa-solid fa-star" style="color: gold"></i>
                      {% endif %} {% if session.coach.rating > 2%}
                      <i class="fa-solid fa-star" style="color: gold"></i>
                      {% endif %} {% if session.coach.rating > 3%}
                      <i class="fa-solid fa-star" style="color: gold"></i>
                      {% endif %} {% if session.coach.rating > 4%}
                      <i class="fa-solid fa-star" style="color: gold"></i>
                      {% endif %} {{session.coach.id}}
                    </div>
                  </div>
                  <div>
                    <i class="bi bi-geo-alt-fill"></i>
                    <span>{{session.coach.location}}</span>
                  </div>
                </div>
              </div>
              <div>
                <div>
                  <div class="m-2">
                    <i class="bi bi-calendar-date"></i>
                    <span>{{session.time}}</span>
                  </div>
                  <div class="m-2">
                    <i class="bi bi-clock"></i>
                    <span>{{session.duration}} Min</span>
                  </div>

                  <div class="m-2">
                    {% if session.group_session %}
                    <i class="bi bi-people"></i>
                    <span>Group Session</span>
                    <span class="badge bg-primary rounded-pill"
                      >{{session.id}}</span
                    >
                    {% else %}
                    <span>Private Session</span>
                    {% endif %}
                  </div>
                </div>
              </div>
              <div>
                <div class="d-flex flex-column gap-2">
                  <div class="w-100">
                    <a
                      href="{% url 'coach_details' session.coach.id %}"
                      class="btn custom-btn-outline-primary"
                    >
                      VIEW COACH PROFILE
                    </a>
                  </div>
                  <div class="w-100">
                    <a
                      href="{% url 'booking' pk=session.coach.id %}"
                      class="btn custom-btn-primary w-100"
                    >
                      BOOK APPOINTMENT
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}